// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abilitiesBlock': string;
  'imgCard': string;
  'infoBlock': string;
  'infoPart': string;
  'root': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
