// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'contentParallax': string;
  'root': string;
  'rootWrapper': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
